### PR TITLE
put common goals into submenu

### PR DESCRIPTION
**Pull request by Eskibear**

### CODE REVIEW

**Comment by Eskibear** [comment]
image

**Comment by nickzhums** [comment]
is it possible to put a dotted line, or just a line to group the "most common" goals together? for example, i imagine "clean package install" will be way more popular than "test, compile, deploy".

**Comment by Eskibear** [comment]
Technically it's feasible to do that.. For each entry here we register a corresponding command. If you do think that's necessary, then we need a list of those popular commands.

**Comment by nickzhums** [comment]
Can we do this 

image

**Comment by Eskibear** [comment]
yes, of course.

**Comment by Eskibear** [comment]
image

@nickzhums Are you OK with it?

**Review by nickzhums — APPROVED** [review]

**Pull request merged**
