### PR TITLE
register 'execute commands' onto Project Manager

### PR DESCRIPTION
**Pull request by Eskibear**
Requires https://github.com/microsoft/vscode-java-dependency/pull/311

image

### CODE REVIEW

**Comment by Eskibear** [comment]
Note that the wording "execute commands..." here might be not clear enough. 
In Maven extension, the full name of the command (in command palette) is "Maven: execute commands...", because the `group` is "Maven".

**Comment by jdneo** [comment]
Will you consider change it to `Execute Maven Commands...`? IMO, trigger the command from Maven & Project explorer may be more frequency than in command palette.

**Comment by Eskibear** [comment]
Then the side effect would be "Maven: Execute Maven Commands..." in command palette. And yes it's OK for me.

**Comment by jdneo** [comment]
So now we have three possible solution per offline discussion:

- Change to `Maven: Execute Maven Commands...`
- Wrap another command for tree view usage
- Open a ticket to VS Code about adding a treeview display name for a command

**Comment by Eskibear** [comment]
Now using an alias command `maven.goal.execute.fromProjectManager` for the same functionality. 

image

**Review by jdneo — APPROVED** [review]

**Pull request merged**
