### PR TITLE
use TreeItem.description to provide show identifier

### PR DESCRIPTION
**Pull request by Eskibear**
Related issue: #590 

Solution:
- Maven items
  - label: show "name" if provided, "artifactId" as fallback.
  - description: always show groupId : artifactId. (version is omitted as I don't think it's that important in distinguishing)
- Plugin items
  - before resolving it to get detailed info (e.g. prefix), show qualified id, aka. groupId:artifactId:version
  - show "prefix" if resolved, and put qualified id in description

After this PR:
image

### CODE REVIEW

**Comment by jdneo** [comment]
In the screenshot, there are some description shows as `undefined:xxx`, when will the `undefined` appear?

**Comment by Eskibear** [comment]
Good catch. The case should be when group id is not defined directly in POM, but is inherited from parent POM.

**Comment by jdneo** [comment]
So I guess we need to find some approach to handle this right?

**Comment by Eskibear** [comment]
1. Simplest. If group Id is missing, it's omitted. Because artifact Id must exist, we only show artifact id.
2. Traverse parent POMs above.

**Comment by Eskibear** [comment]
image

@jdneo , please take a look, I adopt option 2) to traverse parents

**Review by jdneo — APPROVED** [review]

**Pull request merged**
